course_name = "最优估计"
course_code = "AUTO5013"
notices = ""

[[lecturers]]
name = "许鋆"
[lecturers.author]
name = ""
link = ""
date = ""

textbooks = []
online_resources = []
course = []

[[exam]]
content = """
可带一张 A4 纸。
以作业题、课堂例题为主，基本比较简单，但也会有一道较难的题。
"""
[exam.author]
name = ""
link = ""
date = ""

advice = []
schedule = []
related_links = []

[[misc]]
content = "成绩构成：作业10%，出勤10%，项目40%，期末考试40%。"
[misc.author]
name = ""
link = ""
date = ""